// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prodservice.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProdsRequest struct {
	Size                 int32    `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdsRequest) Reset()         { *m = ProdsRequest{} }
func (m *ProdsRequest) String() string { return proto.CompactTextString(m) }
func (*ProdsRequest) ProtoMessage()    {}
func (*ProdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e0f1ea923c64a34, []int{0}
}

func (m *ProdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdsRequest.Unmarshal(m, b)
}
func (m *ProdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdsRequest.Marshal(b, m, deterministic)
}
func (m *ProdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdsRequest.Merge(m, src)
}
func (m *ProdsRequest) XXX_Size() int {
	return xxx_messageInfo_ProdsRequest.Size(m)
}
func (m *ProdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProdsRequest proto.InternalMessageInfo

func (m *ProdsRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ProdsResponse struct {
	Data                 []*ProdModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProdsResponse) Reset()         { *m = ProdsResponse{} }
func (m *ProdsResponse) String() string { return proto.CompactTextString(m) }
func (*ProdsResponse) ProtoMessage()    {}
func (*ProdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e0f1ea923c64a34, []int{1}
}

func (m *ProdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdsResponse.Unmarshal(m, b)
}
func (m *ProdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdsResponse.Marshal(b, m, deterministic)
}
func (m *ProdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdsResponse.Merge(m, src)
}
func (m *ProdsResponse) XXX_Size() int {
	return xxx_messageInfo_ProdsResponse.Size(m)
}
func (m *ProdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProdsResponse proto.InternalMessageInfo

func (m *ProdsResponse) GetData() []*ProdModel {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ProdsRequest)(nil), "protos.ProdsRequest")
	proto.RegisterType((*ProdsResponse)(nil), "protos.ProdsResponse")
}

func init() {
	proto.RegisterFile("prodservice.proto", fileDescriptor_0e0f1ea923c64a34)
}

var fileDescriptor_0e0f1ea923c64a34 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x4f,
	0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03,
	0x53, 0xc5, 0x52, 0xbc, 0xb9, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0x50, 0x61, 0x25, 0x25, 0x2e, 0x9e,
	0x00, 0x90, 0xda, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xe0, 0xcc,
	0xaa, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0xc9, 0x8c, 0x8b, 0x17, 0xaa,
	0xa6, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x95, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x51, 0x82,
	0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x10, 0x62, 0x54, 0xb1, 0x1e, 0x48, 0x91, 0x6f, 0x7e, 0x4a,
	0x6a, 0x4e, 0x10, 0x58, 0xda, 0xc8, 0x8b, 0x8b, 0x1b, 0x24, 0x14, 0x0c, 0x71, 0x87, 0x90, 0x35,
	0x17, 0x8f, 0x7b, 0x6a, 0x09, 0xd8, 0x24, 0x9f, 0xcc, 0xe2, 0x12, 0x21, 0x11, 0x64, 0x7d, 0x30,
	0x07, 0x48, 0x89, 0xa2, 0x89, 0x42, 0xac, 0x4c, 0x82, 0x38, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xec, 0x11, 0x1a, 0xc7, 0xda, 0x00, 0x00, 0x00,
}
