// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prods.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProdModel struct {
	// @inject_tag: json:"pid"
	ProdId int32 `protobuf:"varint,1,opt,name=ProdId,proto3" json:"pid"`
	// @inject_tag: json:"pname"
	ProdName             string   `protobuf:"bytes,2,opt,name=ProdName,proto3" json:"pname"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdModel) Reset()         { *m = ProdModel{} }
func (m *ProdModel) String() string { return proto.CompactTextString(m) }
func (*ProdModel) ProtoMessage()    {}
func (*ProdModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbbf742de0b26a4, []int{0}
}

func (m *ProdModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdModel.Unmarshal(m, b)
}
func (m *ProdModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdModel.Marshal(b, m, deterministic)
}
func (m *ProdModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdModel.Merge(m, src)
}
func (m *ProdModel) XXX_Size() int {
	return xxx_messageInfo_ProdModel.Size(m)
}
func (m *ProdModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdModel.DiscardUnknown(m)
}

var xxx_messageInfo_ProdModel proto.InternalMessageInfo

func (m *ProdModel) GetProdId() int32 {
	if m != nil {
		return m.ProdId
	}
	return 0
}

func (m *ProdModel) GetProdName() string {
	if m != nil {
		return m.ProdName
	}
	return ""
}

type ProdsRequest struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProdsRequest) Reset()         { *m = ProdsRequest{} }
func (m *ProdsRequest) String() string { return proto.CompactTextString(m) }
func (*ProdsRequest) ProtoMessage()    {}
func (*ProdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbbf742de0b26a4, []int{1}
}

func (m *ProdsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdsRequest.Unmarshal(m, b)
}
func (m *ProdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdsRequest.Marshal(b, m, deterministic)
}
func (m *ProdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdsRequest.Merge(m, src)
}
func (m *ProdsRequest) XXX_Size() int {
	return xxx_messageInfo_ProdsRequest.Size(m)
}
func (m *ProdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProdsRequest proto.InternalMessageInfo

func (m *ProdsRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ProdsResponse struct {
	Data                 []*ProdModel `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProdsResponse) Reset()         { *m = ProdsResponse{} }
func (m *ProdsResponse) String() string { return proto.CompactTextString(m) }
func (*ProdsResponse) ProtoMessage()    {}
func (*ProdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfbbf742de0b26a4, []int{2}
}

func (m *ProdsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProdsResponse.Unmarshal(m, b)
}
func (m *ProdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProdsResponse.Marshal(b, m, deterministic)
}
func (m *ProdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProdsResponse.Merge(m, src)
}
func (m *ProdsResponse) XXX_Size() int {
	return xxx_messageInfo_ProdsResponse.Size(m)
}
func (m *ProdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProdsResponse proto.InternalMessageInfo

func (m *ProdsResponse) GetData() []*ProdModel {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ProdModel)(nil), "models.ProdModel")
	proto.RegisterType((*ProdsRequest)(nil), "models.ProdsRequest")
	proto.RegisterType((*ProdsResponse)(nil), "models.ProdsResponse")
}

func init() {
	proto.RegisterFile("prods.proto", fileDescriptor_cfbbf742de0b26a4)
}

var fileDescriptor_cfbbf742de0b26a4 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x4f,
	0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x29, 0x56,
	0xb2, 0xe7, 0xe2, 0x0c, 0x28, 0xca, 0x4f, 0xf1, 0x05, 0xf1, 0x84, 0xc4, 0xb8, 0xd8, 0x40, 0x1c,
	0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x28, 0x4f, 0x48, 0x8a, 0x8b, 0x03, 0xc4,
	0xf2, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x95, 0x94, 0xb8,
	0x78, 0x40, 0xec, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xe2,
	0xcc, 0xaa, 0x54, 0xa8, 0x09, 0x60, 0xb6, 0x92, 0x19, 0x17, 0x2f, 0x54, 0x4d, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0xaa, 0x90, 0x2a, 0x17, 0x4b, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0xa3, 0x02, 0xb3, 0x06,
	0xb7, 0x91, 0xa0, 0x1e, 0xc4, 0x31, 0x7a, 0x70, 0x97, 0x04, 0x81, 0xa5, 0x93, 0xd8, 0xc0, 0x6e,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x6c, 0x3c, 0x3c, 0xba, 0x00, 0x00, 0x00,
}
